#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Gera a versão em inglês do site a partir dos originais em português.

  docs/index.html  + pipeline/en/strings_html.py  → docs/en.html
  docs/app.js      + pipeline/en/strings_js.py    → docs/app.en.js
  docs/data/wiki.json                              → docs/data/wiki_en.json
  pipeline/en/whoswho.html + primer.html (Who's who, Brazil primer) inseridos em en.html
  pipeline/en/posts_en.json  (títulos e subtítulos das crônicas em inglês → window.POSTS_EN)

Tradução por substituição de trechos exatos: se um trecho da tabela não for
encontrado no original (ou for encontrado mais de uma vez sem "all"), o build
FALHA. É proposital: sinaliza que o original mudou e a tradução precisa de
revisão. Nunca edite en.html / app.en.js / wiki_en.json à mão.

Uso: python3 pipeline/build_en.py [--js-only] [--check]
"""
import json, re, sys, pathlib
ROOT = pathlib.Path(__file__).resolve().parent.parent
DOCS = ROOT/"docs"
sys.path.insert(0, str(ROOT/"pipeline"/"en"))

def apply(text, table, label):
    errs = []
    for item in table:
        pt, en = item[0], item[1]
        mode = item[2] if len(item) > 2 else "one"
        n = text.count(pt)
        if n == 0:
            errs.append(f"{label}: trecho NÃO encontrado (o original mudou?):\n    {pt[:110]!r}")
        elif n > 1 and mode != "all":
            errs.append(f"{label}: trecho ocorre {n}× (marque \"all\" ou torne-o único):\n    {pt[:110]!r}")
        else:
            text = text.replace(pt, en)
    if errs:
        sys.exit("BUILD EN FALHOU\n" + "\n".join(errs))
    return text

ROLE_EN = {"pessoa":"Person","empresa":"Company","autoridade":"Official","advogado":"Lawyer"}
def wiki_en(w):
    out = {"gerado_em": w["gerado_em"], "pages": []}
    for p in w["pages"]:
        q = dict(p)
        proc_txt = ", ".join(f"{pr} ({c})" for pr, c in p["pe"][:5])
        s = (f"{p['label']} appears in {p['docs']} narrative filings across {p['procs']} of the 15 proceedings, "
             f"most often in {proc_txt}. The pipeline classifies it as {ROLE_EN.get(p['papel'], p['papel'])}. ")
        if p.get("peak"): s += f"The dates cited on the pages where the name appears cluster around {p['peak']}. "
        br = p.get("byrole", {})
        if br.get("pessoa"):
            s += f"Most frequently shares pages with {br['pessoa'][0]['label']}"
            s += f" and, among companies, with {br['empresa'][0]['label']}." if br.get("empresa") else "."
        elif br.get("empresa"):
            s += f"Among companies, most frequently shares pages with {br['empresa'][0]['label']}."
        q["resumo"] = s.strip()
        out["pages"].append(q)
    return out

def main():
    js_only = "--js-only" in sys.argv
    check = "--check" in sys.argv
    from strings_js import JS
    app = apply((DOCS/"app.js").read_text(encoding="utf-8"), JS, "app.js")
    if not check: (DOCS/"app.en.js").write_text(app, encoding="utf-8")
    print(f"app.en.js: {len(JS)} substituições OK")
    if js_only: return
    from strings_html import HTML
    html = apply((DOCS/"index.html").read_text(encoding="utf-8"), HTML, "index.html")
    secs = "\n\n".join((ROOT/"pipeline"/"en"/f).read_text(encoding="utf-8") for f in ("whoswho.html","primer.html"))
    # {{sel:Rótulo}} → id do nó (link "abrir no grafo"); falha se o rótulo não existir na base
    w = json.load(open(DOCS/"data"/"wiki.json", encoding="utf-8"))
    g = json.load(open(DOCS/"data"/"graph.json", encoding="utf-8"))
    ids = {n["label"]: n["id"] for n in g["nodes"] if n.get("vis")}
    def sel(m):
        lab = m.group(1)
        if lab not in ids: sys.exit(f"BUILD EN FALHOU: rótulo sem nó visível no grafo: {lab!r}")
        return ids[lab]
    secs = re.sub(r"\{\{sel:([^}]+)\}\}", sel, secs)
    pen = json.load(open(ROOT/"pipeline"/"en"/"posts_en.json", encoding="utf-8"))
    posts = json.load(open(DOCS/"posts"/"index.json", encoding="utf-8"))["posts"]
    faltam = [x["slug"] for x in posts if x["slug"] not in pen] + [x["serie"] for x in posts if x.get("serie") and x["serie"] not in pen["_series"]]
    if faltam: print("aviso: crônicas/séries sem título em inglês (ficam em português):", sorted(set(faltam)))
    chron = '<script>window.POSTS_EN=' + json.dumps(pen, ensure_ascii=False) + '</script>' 
    assert html.count('<section id="v-rede"') == 1 and html.count('<div id="crCards"></div>') == 1
    html = html.replace('<section id="v-rede"', secs.rstrip()+"\n\n"+'<section id="v-rede"', 1)
    html = html.replace('<div id="crCards"></div>', chron.rstrip()+"\n    "+'<div id="crCards"></div>', 1)
    html = html.replace("<!doctype html>", "<!doctype html>\n<!-- GENERATED by pipeline/build_en.py from index.html. Edit index.html and pipeline/en/, not this file. -->", 1)
    left = re.findall(r"[çãõ]", re.sub(r"<[^>]+>", "", html))
    if not check:
        (DOCS/"en.html").write_text(html, encoding="utf-8")
        json.dump(wiki_en(w), open(DOCS/"data"/"wiki_en.json", "w", encoding="utf-8"), ensure_ascii=False, separators=(",", ":"))
    print(f"en.html: {len(HTML)} substituições OK; wiki_en.json: {len(w['pages']) if not check else '-'} fichas")
    if left: print(f"aviso: {len(left)} caracteres ç/ã/õ restantes no texto visível de en.html (nomes próprios são esperados)")

if __name__ == "__main__":
    main()
