# -*- coding: utf-8 -*-
"""Curadoria dos excertos: que trecho de que ato do juízo aparece no site.

Nada aqui é o texto do excerto. Cada entrada aponta onde ele está e por onde começa:

  proc  processo (como no acervo)
  seq   número da peça
  pag   página dentro da peça
  q     trecho-âncora, literal, como está na página; tem de ocorrer uma única vez nela
  n     quantos caracteres pegar a partir da âncora (o corte cai na pontuação seguinte)
  ate   alternativa a `n`: trecho literal onde o excerto termina (incluído)
  t     título curto, nosso, do que o trecho diz
  ctx   uma frase de contexto, nossa, para quem não leu o processo
  ents  entidades citadas, pelo rótulo exato do grafo (o build falha se não existir)

`stage9_excertos.py` busca a âncora no texto da própria peça e falha se não encontrar.
Só atos assinados por autoridade podem ser citados: decisão, despacho, acórdão e manifestação
da Procuradoria. Representação policial e petição de defesa ficam de fora.
"""

EXCERTOS = [
 dict(proc="RCL 88121", seq=91, pag=8, 
      q="Verificando-se, no curso ou na deflagração de investigação penal", ate="impõe-se o imediato envio dos autos ao Supremo Tribunal Federal.", 
      t="O relator diz quando a investigação tem de subir ao Supremo", 
      ctx="A reclamação sustentava que a apreensão de um documento ligado a um deputado federal deslocava o caso para o Supremo. Este é o critério que a decisão adota.", 
      ents=["Dias Toffoli"]),
 dict(proc="RCL 88121", seq=91, pag=22, 
      q="Por fim, para garantir o regular funcionamento das instituições financeiras envolvidas", ate="Assim, deve o Banco Central fornecer a documentação e os elementos informativos relativos aos procedimentos administrativos em curso envolvendo as instituições investigadas.", 
      t="O relator manda o Banco Central entregar o que tem sobre as instituições investigadas", 
      ctx="A liminar de dezembro de 2025 trata também do lado regulatório do caso: o Banco Central é a autoridade que fiscaliza os bancos envolvidos.", 
      ents=["Dias Toffoli"]),
 dict(proc="RCL 88121", seq=91, pag=23, 
      q="Nesse contexto, e sem prejuízo de melhor análise do direito após a instrução do processo", ate="até o julgamento definitivo da presente reclamação.", 
      t="A liminar suspende a investigação na primeira instância e chama o caso para o Supremo", 
      ctx="É o dispositivo da decisão de 9 de dezembro de 2025, que tirou a operação da 10ª Vara Federal de Brasília e passou sua supervisão ao Supremo.", 
      ents=["Dias Toffoli"]),
 dict(proc="RCL 88121", seq=113, pag=7, 
      q="REITERO, OUTROSSIM, O DEFERIMENTO DAS QUEBRAS DE SIGILO", ate="devendo as informações serem encaminhadas ao Supremo Tribunal Federal.", 
      t="O relator mantém as quebras de sigilo da CPMI e chama as informações para si", 
      ctx="Três dias depois da liminar, a defesa pediu a anulação das quebras de sigilo aprovadas pela CPMI do INSS. A decisão não as anula e redireciona os dados ao Supremo.", 
      ents=["Dias Toffoli", "Cpmi do Inss"]),
 dict(proc="RCL 88121", seq=152, pag=1, 
      q="DETERMINO a realização imediata das seguintes diligências preliminares", ate="as denúncias em apuração nestes autos;", 
      t="O relator fixa trinta dias e manda ouvir os investigados", 
      ctx="Com a investigação já sob supervisão do Supremo, a decisão de 15 de dezembro de 2025 lista quatro diligências urgentes; esta é a primeira delas.", 
      ents=["Dias Toffoli", "Banco Master"]),
 dict(proc="RCL 88121", seq=237, pag=17, 
      q="Ante o exposto, julgo parcialmente procedente a presente reclamação", ate="inclusive as constrições sobre bens e valores.", 
      t="A reclamação é julgada procedente em parte e o Supremo fica com a supervisão", 
      ctx="É o dispositivo da decisão final da reclamação, de 22 de dezembro de 2025, que confirmou a liminar quanto à competência.", 
      ents=["Dias Toffoli"]),
 dict(proc="INQ 5026", seq=323, pag=6, 
      q="Ante o exposto, e inexistindo, até o presente momento, oposição da defesa", ate="dependerá de sua anuência explícita.", 
      t="O relator autoriza o depoimento no Senado, mas só se o investigado quiser", 
      ctx="A Comissão de Assuntos Econômicos do Senado pediu autorização para ouvir o investigado preso. A decisão de 19 de fevereiro de 2026 responde ao pedido.", 
      ents=["André Mendonça", "Daniel Bueno Vorcaro"]),
 dict(proc="INQ 5026", seq=391, pag=3, 
      q="Reitera-se expressamente a determinação para que a Polícia Federal fixe as condições logísticas", ate="sendo vedado o deslocamento em qualquer aeronave particular.", 
      t="O relator fixa como deve ser o transporte do investigado até o Senado", 
      ctx="Ao estender a autorização para uma segunda sessão da comissão do Senado, a decisão repete a regra de escolta e veda avião particular.", 
      ents=["André Mendonça", "Daniel Bueno Vorcaro"]),
 dict(proc="INQ 5026", seq=423, pag=15, 
      q="Ocorre que, pelas informações de que se dispõe até o presente momento", ate="no âmbito da denominada Operação Compliance Zero.", 
      t="O relator não vê indício que ligue o ex-presidente do Banco Central ao caso", 
      ctx="A CPI do Crime Organizado convocou o ex-presidente do Banco Central tendo o colapso do Banco Master como justificativa. A decisão examina esse vínculo.", 
      ents=["André Mendonça"]),
 dict(proc="INQ 5026", seq=423, pag=16, 
      q="Nada obstante, buscando conferir solução embasada na diretriz hermenêutica", ate="nos exatos termos realizados em relação ao atual presidente do Banco Central do Brasil.", 
      t="O relator transforma a convocação da CPI em convite", 
      ctx="Em vez de anular a deliberação do Senado, a decisão de 2 de março de 2026 reduz seus efeitos, seguindo o que já havia sido decidido para o atual presidente do Banco Central.", 
      ents=["André Mendonça"]),
 dict(proc="INQ 5026", seq=453, pag=5, 
      q="Ante o exposto, estando patente a objeção da defesa de DANIEL BUENO VORCARO", n=330, 
      t="O relator torna facultativo o depoimento na CPI do Crime Organizado", 
      ctx="A comissão pediu que o comparecimento fosse obrigatório e a defesa pediu o contrário. A decisão de 3 de março de 2026 escolhe entre os dois pedidos.", 
      ents=["André Mendonça", "Daniel Bueno Vorcaro"]),
 dict(proc="PET 15198", seq=14, pag=12, 
      q="O fluxograma demonstra que, apesar da BRAIN REALTY passasse a dever", ate="R$ 450 milhões em CDBs", 
      t="A decisão descreve o dinheiro saindo e voltando ao Banco Master", 
      ctx="A decisão reproduz a representação do Banco Central que descreve o circuito de recursos entre o Banco Master e fundos ligados à REAG.", 
      ents=["Banco Master", "Reag Growth"]),
 dict(proc="PET 15198", seq=14, pag=15, 
      q="Portanto, o valor de R$ 302.586.000,00 deve recair sobre essas pessoas físicas", n=270, 
      t="O bloqueio alcança o Banco Master como cotista único do fundo", 
      ctx="Ao fixar sobre quem recai o sequestro relativo ao FIDIC CITY, a decisão registra que o próprio Banco Master era o único cotista do fundo.", 
      ents=["Banco Master", "Daniel Bueno Vorcaro"]),
 dict(proc="PET 15198", seq=14, pag=19, 
      q="Por todo o exposto, defiro os pedidos de quebras de sigilo bancário", ate="tal como requeridos pelo Procurador-Geral da República em sua manifestação", 
      t="O relator defere as quebras de sigilo e o bloqueio de bens", 
      ctx="É o dispositivo da decisão de 6 de janeiro de 2026, que abriu a segunda fase da investigação sobre o destino do dinheiro captado pelo Banco Master.", 
      ents=["Dias Toffoli"]),
 dict(proc="PET 15198", seq=21, pag=5, 
      q="Ressalto que o Banco Master S.A. encontra-se em regime de liquidação extrajudicial", ate="sem a necessidade de novas diligências in loco", 
      t="O relator nega busca na sede do banco já sob liquidação", 
      ctx="Ao deferir apenas em parte os pedidos complementares de busca e apreensão, a decisão explica por que dispensou novas diligências na sede do Banco Master.", 
      ents=["Banco Master", "Dias Toffoli"]),
 dict(proc="PET 15198", seq=403, pag=10, 
      q="Por fim, determino que a instauração de qualquer nova investigação ou inquérito", ate="aplicando-se o sigilo padrão, nível III", 
      t="O relator condiciona novas investigações à sua autorização prévia", 
      ctx="A decisão organiza o trabalho da Polícia Federal na segunda fase da Operação Compliance Zero e fixa o nível de sigilo dos autos.", 
      ents=["André Mendonça"]),
 dict(proc="PET 15198", seq=1012, pag=9, 
      q="A juntada do certificado de registro e licenciamento do veículo", ate="a capacidade econômica lícita dos requerentes", 
      t="O documento do carro não prova a origem lícita do dinheiro", 
      ctx="É o fundamento pelo qual o relator manteve apreendidos veículos de luxo cuja devolução era pedida por dois investigados.", 
      ents=["André Mendonça", "Henrique Moura Vorcaro", "Thiago Assumpção Henriques"]),
 dict(proc="INQ 5035", seq=6, pag=6, 
      q="Inicialmente, enfatizo que, na gestão dos dados obtidos", ate="própria às atividades de inteligência e de polícia judiciária", 
      t="O relator exige compartimentação das informações", 
      ctx="Decisão de 19 de fevereiro de 2026 sobre a perícia do material apreendido na Operação Compliance Zero, em inquérito que apura, segundo consta dos autos, suposta campanha difamatória de influenciadores digitais contra o Banco Central.", 
      ents=["André Mendonça"]),
 dict(proc="INQ 5035", seq=6, pag=8, 
      q="Como decorrência do acima exposto, frisa-se que apenas e tão somente", ate="superiores hierárquicos e outras autoridades públicas.", 
      t="O sigilo vale até diante dos superiores hierárquicos", 
      ctx="A decisão restringe o conhecimento das informações aos policiais que conduzem o caso.", 
      ents=["André Mendonça"]),
 dict(proc="INQ 5035", seq=6, pag=9, 
      q="Em relação à Diretoria de Inteligência da Polícia Federal", ate="guardem relação com as respectivas apurações;", 
      t="A Diretoria de Inteligência só fala com os delegados do caso", 
      ctx="No resumo do que autorizou, o relator delimita o fluxo entre a inteligência da Polícia Federal e os responsáveis pela investigação.", 
      ents=["André Mendonça"]),
 dict(proc="INQ 5035", seq=33, pag=1, 
      q="Constatada a necessidade das diligências por parte da autoridade policial", ate="Após, tornem conclusos.", 
      t="O relator prorroga o inquérito por 60 dias", 
      ctx="Despacho de 31 de março de 2026, que devolve os autos à Polícia Federal pelo prazo pedido.", 
      ents=["André Mendonça"]),
 dict(proc="PET 15478", seq=17, pag=3, 
      q="De outro bordo, é cediço que a tutela constitucional da intimidade", n=300, 
      t="O relator afirma que a intimidade não é direito absoluto", 
      ctx="É o fundamento constitucional invocado para autorizar o afastamento dos sigilos bancário e fiscal dos investigados.", 
      ents=["André Mendonça"]),
 dict(proc="PET 15478", seq=17, pag=4, 
      q="Com isso, o BRB teria transferido cerca de R$ 17 bilhões", ate="não conseguir auditar adequadamente por falta de documentação", 
      t="A decisão registra quanto o BRB transferiu ao banco privado", 
      ctx="Ao expor o que a Polícia Federal e a Procuradoria apuraram, a decisão que quebrou os sigilos dimensiona as operações entre o BRB e o Banco Master.", 
      ents=["Banco Brb", "Banco Master"]),
 dict(proc="PET 15478", seq=17, pag=14, 
      q="Ante o exposto, DEFIRO os requerimentos formulados pela autoridade policial", ate="por outro sistema ou meio de comunicação equivalente", 
      t="O relator quebra o sigilo bancário por dois anos de movimentação", 
      ctx="É o dispositivo da decisão de 22 de junho de 2026, que atingiu nove pessoas físicas e quatro empresas listadas na representação policial.", 
      ents=["André Mendonça"]),
 dict(proc="PET 15478", seq=17, pag=16, 
      q="No que respeita ao afastamento do sigilo fiscal", ate="a contar da data do recebimento do ofício", 
      t="O relator dá trinta dias à Receita Federal para entregar os dados", 
      ctx="A decisão detalha como a quebra do sigilo fiscal deve ser cumprida e fixa o prazo de entrega das informações.", 
      ents=["André Mendonça"]),
 dict(proc="PET 15504", seq=14, pag=1, 
      q="Indefiro, de plano, o pedido de acesso aos autos pelos advogados", ate="porquanto seus representandos não são investigados neste feito específico", 
      t="O relator nega acesso aos autos a quem não é investigado ali", 
      ctx="A decisão limita quem pode consultar o procedimento sigiloso aberto contra dois servidores da supervisão bancária.", 
      ents=["André Mendonça"]),
 dict(proc="PET 15504", seq=18, pag=1, 
      q="A Polícia Federal representa pela instauração de PET sigilosa em apartado", ate="BELLINE SANTANA", 
      t="A investigação apura corrupção entre o banco e servidores do Banco Central", 
      ctx="O despacho descreve o objeto da representação policial que deu origem ao procedimento sigiloso apartado.", 
      ents=["Daniel Bueno Vorcaro", "Belline Santana"]),
 dict(proc="PET 15504", seq=18, pag=1, 
      q="Ouvida, a Procuradoria-Geral da República manifesta-se pelo acolhimento do pedido", ate="do Supremo Tribunal Federal", 
      t="O relator autoriza a apuração com apoio da Procuradoria", 
      ctx="A decisão registra a concordância da Procuradoria-Geral da República e a norma regimental em que se apoia a abertura do procedimento.", 
      ents=["André Mendonça"]),
 dict(proc="PET 15504", seq=73, pag=2, 
      q="Com fulcro no artigo 230-C, § 1º, do RISTF defiro a prorrogação", n=190, 
      t="O relator prorroga a investigação por mais sessenta dias", 
      ctx="Atendendo a pedido da Polícia Federal, a decisão estende o prazo das diligências no procedimento sobre os servidores do Banco Central.", 
      ents=["André Mendonça"]),
 dict(proc="PET 15556", seq=16, pag=3, 
      q="Sobre a petição da Procuradoria-Geral da República, antecipo", n=230, 
      t="O relator nega mais prazo à Procuradoria", 
      ctx="A Procuradoria-Geral da República pediu que as medidas aguardassem sua manifestação; nesta passagem o relator indefere o pedido e remete os motivos ao capítulo de mérito.", 
      ents=["André Mendonça"]),
 dict(proc="PET 15556", seq=16, pag=26, 
      q="Nos termos do que tenho considerado nos feitos de natureza penal", n=250, 
      t="O relator ressalva que a prisão cautelar não é juízo de certeza", 
      ctx="Ao iniciar a fundamentação da prisão preventiva, o relator registra em que padrão de convicção a decisão é tomada.", 
      ents=["André Mendonça"]),
 dict(proc="PET 15556", seq=16, pag=30, 
      q="Diante desse robusto quadro fático-probatório, lamenta-se que a PGR diga", ate="“no mais breve tempo possível”.", 
      t="O relator expõe por que discorda da Procuradoria", 
      ctx="No capítulo de mérito, o relator retoma a petição da Procuradoria-Geral da República e explica por que considerou que o caso não comportava espera.", 
      ents=["André Mendonça"]),
 dict(proc="PET 15556", seq=16, pag=31, 
      q="Posto esse quadro, as medidas menos gravosas previstas em nosso ordenamento", n=560, 
      t="O relator afasta as medidas mais brandas", 
      ctx="Este é o fundamento central do decreto: por que, no entender do relator, nenhuma medida alternativa à prisão seria suficiente.", 
      ents=["André Mendonça"]),
 dict(proc="PET 15556", seq=16, pag=40, 
      q="Ante o exposto, com fundamento nos artigos 282, 311 e 312", n=460, 
      t="O relator decreta a prisão preventiva de quatro investigados", 
      ctx="É o dispositivo da decisão de 3 de março de 2026, que deflagrou a terceira fase da Operação Compliance Zero.", 
      ents=["André Mendonça", "Daniel Bueno Vorcaro", "Fabiano Campos Zettel", "Luiz Phillipi Machado de Moraes Mourão", "Marilson Roseno"]),
 dict(proc="PET 15556", seq=16, pag=42, 
      q="DEFIRO, outrossim, com alicerce no art. 319, VI, do CPP", ate="KING MOTORS LOCAÇÃO DE VEÍCULOS E PARTICIPAÇÕES LTDA.", 
      t="O relator suspende por tempo indeterminado as atividades de cinco empresas", 
      ctx="Além das prisões e das medidas cautelares pessoais, a mesma decisão atinge pessoas jurídicas apontadas pela Polícia Federal.", 
      ents=["André Mendonça", "Varajo Consultoria", "Moriah Asset Empreendimentos", "Super Empreendimentos", "King Participacoes Imobiliarias"]),
 dict(proc="PET 15556", seq=16, pag=45, 
      q="Os mandados de prisão deverão ser cumpridos de maneira serena", n=380, 
      t="O relator fixa como os mandados devem ser cumpridos", 
      ctx="A decisão dedica um capítulo à operacionalização das prisões e estabelece o modo de execução dos mandados.", 
      ents=["André Mendonça"]),
 dict(proc="PET 15556", seq=43, pag=3, 
      q="DEFIRO o pedido formulado pela Polícia Federal para autorizar", ate="atendimentos médicos e demais deslocamentos necessários.", 
      t="O relator manda os presos para o sistema penitenciário estadual", 
      ctx="No dia seguinte ao decreto, a Polícia Federal informou que suas unidades de trânsito não comportam custódia prolongada e pediu a transferência dos presos.", 
      ents=["André Mendonça"]),
 dict(proc="PET 15556", seq=261, pag=2, 
      q="A Turma, por unanimidade, referendou a liminar concedida", ate="Afirmou suspeição o Ministro Dias Toffoli.", 
      t="A Segunda Turma referenda o decreto de prisão", 
      ctx="Certidão da sessão virtual de 13 a 20 de março de 2026, em que o colegiado apreciou o referendo da decisão do relator.", 
      ents=["André Mendonça", "Gilmar Mendes", "Dias Toffoli", "Luiz Phillipi Machado de Moraes Mourão"]),
 dict(proc="PET 15556", seq=441, pag=5, 
      q="Ante o exposto, acolho o parecer da Procuradoria-Geral da República para declarar extinta", ate="determinar o arquivamento parcial das investigações.", 
      t="O relator declara extinta a punibilidade do investigado que morreu", 
      ctx="Um dos quatro presos pela decisão de março morreu; em 29 de maio de 2026 o relator decidiu o efeito do óbito, mantendo, na mesma decisão, o sequestro de bens e valores que recaía sobre ele.", 
      ents=["André Mendonça", "Luiz Phillipi Machado de Moraes Mourão"]),
 dict(proc="PET 15562", seq=18, pag=1, 
      q="Trata-se de representação formulada pela Polícia Federal", ate="vinculados ao esquema investigado.", 
      t="O relator descreve o objeto do pedido de busca", 
      ctx="É a abertura da decisão que autorizou as buscas da terceira fase da Operação Compliance Zero, em 3 de março de 2026.", 
      ents=["André Mendonça", "Banco Master"]),
 dict(proc="PET 15562", seq=18, pag=13, 
      q="A detida análise da extensa peça de representação apresentada", ate="(fortes indícios de autoria e materialidade delitiva).", 
      t="O relator dá por presentes os indícios que autorizam a busca", 
      ctx="A decisão indica quais provas já reunidas pela Polícia Federal sustentam, a seu ver, o requisito de indícios de autoria e materialidade.", 
      ents=["André Mendonça"]),
 dict(proc="PET 15562", seq=18, pag=17, 
      q="DEFIRO a medida de busca e apreensão nos termos", ate="nos endereços lá indicados.", 
      t="O relator defere a busca e apreensão contra os alvos da representação", 
      ctx="É o dispositivo da decisão: o relator acolhe o pedido da Polícia Federal em relação à lista de investigados apresentada nos autos.", 
      ents=["André Mendonça"]),
 dict(proc="PET 15562", seq=18, pag=17, 
      q="Os mandados devem ser expedidos observando-se as exigências", ate="arts. 245 a 250 do mesmo diploma legal.", 
      t="O relator manda cumprir os mandados sem espetacularização", 
      ctx="Ao operacionalizar a medida, a decisão fixa o modo de cumprimento dos mandados pela Polícia Federal.", 
      ents=["André Mendonça"]),
 dict(proc="PET 15562", seq=18, pag=19, 
      q="Fica autorizada a busca e apreensão de dinheiro em espécie", ate="tenham origem não justificada ou irregular.", 
      t="A decisão fixa em R$ 20 mil o piso para apreender dinheiro", 
      ctx="A decisão delimita o que pode ser apreendido nos endereços dos investigados, fixando um valor mínimo para o dinheiro em espécie.", 
      ents=["André Mendonça"]),
 dict(proc="PET 15563", seq=17, pag=1, 
      q="Trata-se de representação formulada pela Polícia Federal", ate="vinculados ao esquema investigado.", 
      t="O relator descreve o objeto do pedido de bloqueio de bens", 
      ctx="É a abertura da decisão que, no mesmo 3 de março de 2026, apreciou o pedido de medidas assecuratórias sobre bens dos investigados.", 
      ents=["André Mendonça", "Banco Master", "Daniel Bueno Vorcaro"]),
 dict(proc="PET 15563", seq=17, pag=3, 
      q="Sobre a petição da Procuradoria-Geral da República", n=230, 
      t="O relator nega mais prazo à Procuradoria", 
      ctx="A Procuradoria tinha 24 horas para opinar sobre o bloqueio de bens e pediu mais tempo. A decisão registra que o prazo já havia passado.", 
      ents=["André Mendonça"]),
 dict(proc="PET 15563", seq=17, pag=12, 
      q="A constrição patrimonial pretendida possui caráter assecuratório", ate="da execução de eventual condenação futura.", 
      t="A decisão ressalva que o bloqueio não antecipa juízo de culpa", 
      ctx="Ao justificar a indisponibilidade dos bens, o relator registra o alcance limitado da medida.", 
      ents=["André Mendonça"]),
 dict(proc="PET 15563", seq=17, pag=15, 
      q="Desse modo, o fundamento jurídico da medida repousa", ate="aplicável aos delitos que causam danos à Fazenda Pública.", 
      t="O relator aponta a tríplice base legal do bloqueio", 
      ctx="A decisão resume as três normas em que apoia a constrição de bens dos investigados.", 
      ents=["André Mendonça"]),
 dict(proc="PET 15563", seq=17, pag=16, 
      q="Ante o exposto, acolho os requerimentos da autoridade policial", ate="de ativos financeiros das pessoas jurídicas envolvidas no país,", 
      t="O relator defere o bloqueio de contas e ativos financeiros", 
      ctx="É o início do dispositivo; os valores a bloquear para cada alvo constam de uma tabela da representação policial, que não é pública.", 
      ents=["André Mendonça"]),
 dict(proc="PET 15563", seq=17, pag=19, 
      q="Expeça-se ofício à Superintendência de Seguros Privados", ate="títulos de capitalização e contratos de seguro.", 
      t="O relator dá 48 horas à Susep para bloquear seguros e previdência", 
      ctx="A decisão distribui o cumprimento do bloqueio entre vários órgãos e fixa prazo para cada um; este é o trecho dirigido ao regulador de seguros.", 
      ents=["André Mendonça"]),
 dict(proc="PET 15693", seq=4, pag=4, 
      q="Determino, ainda, que as empresas Apple Computer Brasil", ate="com a preservação dos dados a seguir relacionados:", 
      t="O relator dá 15 dias para Apple e Google informarem o congelamento", 
      ctx="Em março de 2026, antes de pedir o conteúdo, a decisão determinou às duas empresas a preservação imediata dos dados em nuvem dos investigados.", 
      ents=["André Mendonça"]),
 dict(proc="PET 15693", seq=34, pag=16, 
      q="A medida também se revela adequada, necessária e proporcional", ate="em investigação de crimes graves e de atuação organizada.", 
      t="O relator explica por que considera a quebra proporcional", 
      ctx="É o núcleo da fundamentação da decisão que afastou o sigilo telemático de dezessete investigados, em 19 de junho de 2026.", 
      ents=["André Mendonça"]),
 dict(proc="PET 15693", seq=34, pag=20, 
      q="Ante o exposto, DEFIRO a representação formulada pela Polícia Federal", ate="observadas as condições abaixo.", 
      t="O relator defere o afastamento do sigilo telemático", 
      ctx="É o dispositivo da decisão, que acolheu o pedido da Polícia Federal com parecer favorável da Procuradoria-Geral da República.", 
      ents=["André Mendonça"]),
 dict(proc="PET 15693", seq=34, pag=20, 
      q="Determino a expedição de ofício à Apple Computer Brasil", ate="até a data do cumprimento da ordem", 
      t="A ordem à Apple fixa 48 horas e alcança dados desde 2021", 
      ctx="O mesmo prazo de 48 horas e o mesmo recorte temporal foram fixados nos ofícios dirigidos ao Google e à Microsoft.", 
      ents=["André Mendonça"]),
 dict(proc="PET 15693", seq=34, pag=23, 
      q="Defiro, ainda, nos termos requeridos, a criação de conta espelho", ate="que possa frustrar a medida.", 
      t="O relator autoriza conta espelho, sem aviso ao usuário", 
      ctx="O trecho fecha a ordem dirigida à Microsoft; a mesma decisão proíbe as três empresas de comunicar a existência da ordem aos investigados.", 
      ents=["André Mendonça"]),
 dict(proc="PET 15976", seq=34, pag=51, 
      q="a doutrina costuma assinalar que a busca e apreensão, embora invasiva", ate="juízo de probabilidade de que, no local, se encontrem os elementos buscados", 
      t="O relator lista os três requisitos da busca e apreensão", 
      ctx="Antes de decidir sobre as buscas pedidas pela Polícia Federal, a decisão enuncia as condições que entende necessárias para autorizar a medida.", 
      ents=["André Mendonça"]),
 dict(proc="PET 15976", seq=34, pag=54, 
      q="Ressalto, por fim, que o presente exame é perfunctório", n=400, 
      t="O relator ressalva que não há juízo de culpa nesta fase", 
      ctx="Ao encerrar a fundamentação, a decisão registra o alcance limitado do exame feito para autorizar a diligência.", 
      ents=["André Mendonça"]),
 dict(proc="PET 15976", seq=34, pag=56, 
      q="DEFIRO a medida de busca e apreensão nos termos em que requerida", ate="através de petição encartada ao e-Doc. 32 dos autos", 
      t="O relator defere a busca e apreensão contra treze alvos", 
      ctx="É o dispositivo da decisão de 13 de maio de 2026 que autorizou as buscas pedidas pela Polícia Federal na Operação Compliance Zero.", 
      ents=["André Mendonça"]),
 dict(proc="PET 15976", seq=34, pag=57, 
      q="Os mandados devem ser expedidos observando-se as exigências do art. 243", ate="com os preceitos contidos nos arts. 245 a 250 do mesmo diploma legal", 
      t="O relator fixa como os mandados devem ser cumpridos", 
      ctx="A decisão condiciona a execução das buscas a um modo de cumprimento discreto e ao sigilo da investigação.", 
      ents=["André Mendonça"]),
 dict(proc="PET 15976", seq=65, pag=2, 
      q="o pedido complementar formulado pela Polícia Federal para que as buscas", n=420, 
      t="O relator estende a busca à sala funcional da delegada", 
      ctx="Um dia depois da decisão principal, a Polícia Federal pediu que a busca também alcançasse a sala usada por uma delegada na Superintendência em Minas Gerais.", 
      ents=["André Mendonça"]),
 dict(proc="PET 15977", seq=32, pag=12, 
      q="A medida postulada é juridicamente cabível", n=470, 
      t="O relator enumera os requisitos da interceptação", 
      ctx="A decisão expõe as condições que considera cumulativas para autorizar interceptação telefônica e telemática.", 
      ents=["André Mendonça"]),
 dict(proc="PET 15977", seq=32, pag=13, 
      q="A interceptação dos respectivos terminais se mostra particularmente necessária", n=350, 
      t="O relator explica por que a interceptação seria indispensável", 
      ctx="A decisão registra o que, segundo a Polícia Federal, ainda não teria sido alcançado pelos meios de investigação já empregados.", 
      ents=["André Mendonça"]),
 dict(proc="PET 15977", seq=32, pag=15, 
      q="Não se trata de devassa indiscriminada ou de pleito genérico", n=330, 
      t="O relator aponta a delimitação do pedido e o prazo de 15 dias", 
      ctx="Ao tratar da proporcionalidade, a decisão descreve o grau de individualização do pedido apresentado pela Polícia Federal.", 
      ents=["André Mendonça"]),
 dict(proc="PET 15977", seq=32, pag=19, 
      q="DEFIRO a interceptação/monitoramento telemático do WhatsApp", ate="mencionados nas fls. 234-235 da representação da Polícia Federal (e-Doc. 2)", 
      t="O relator defere o monitoramento telemático por 15 dias", 
      ctx="É parte do dispositivo da decisão de 11 de maio de 2026, que autorizou interceptação telefônica e telemática de dez investigados.", 
      ents=["André Mendonça"]),
 dict(proc="PET 15977", seq=32, pag=20, 
      q="O cumprimento da decisão deverá ser feito com observância do que contido nos itens 1 a 11", n=350, 
      t="O relator reserva a si o encerramento das interceptações", 
      ctx="Ao operacionalizar a medida, a decisão altera um dos itens propostos pela Polícia Federal.", 
      ents=["André Mendonça"]),
 dict(proc="PET 15978", seq=32, pag=53, 
      q="as medidas menos gravosas previstas em nosso ordenamento jurídico não ostentam", n=500, 
      t="O relator afasta as medidas menos gravosas para sete investigados", 
      ctx="É o trecho em que a decisão justifica por que entende insuficiente qualquer alternativa à prisão para parte dos investigados.", 
      ents=["André Mendonça"]),
 dict(proc="PET 15978", seq=32, pag=56, 
      q="Ante o exposto, com fundamento nos artigos 282, 311, 312, 319 e 320", ate="DECRETO A PRISÃO PREVENTIVA DOS INVESTIGADOS", 
      t="O relator decreta sete prisões preventivas", 
      ctx="Abertura do dispositivo da decisão de 13 de maio de 2026, depois submetida a referendo da Segunda Turma.", 
      ents=["André Mendonça"]),
 dict(proc="PET 15978", seq=32, pag=57, 
      q="Em relação aos investigados (i) ERLENE NONATO LACERDA", ate="o afastamento preventivo e imediato da função pública de Delegada da Polícia Federal (art. 319, VI, do CPP)", 
      t="O relator manda entregar passaportes em 24 horas e afasta a delegada", 
      ctx="Para cinco investigados não presos, a decisão impôs restrições em vez da prisão, entre elas o afastamento de uma delegada da Polícia Federal.", 
      ents=["André Mendonça", "Erlene Nonato Lacerda", "Katherine Venancio Teles"]),
 dict(proc="PET 15978", seq=32, pag=58, 
      q="Uma vez efetivadas as prisões, os investigados deverão ser apresentados", ate="mediante ajuste direto e apresentação da autoridade policial", 
      t="O relator fixa audiência de custódia em até 24 horas", 
      ctx="A decisão detalha como as prisões devem ser executadas e perante qual juízo os presos devem ser apresentados.", 
      ents=["André Mendonça"]),
 dict(proc="PET 15978", seq=272, pag=3, 
      q="uma vez submetido o decreto prisional a referendo pela Segunda Turma", n=330, 
      t="O relator julga prejudicados os pedidos de revogação da prisão", 
      ctx="Em julho de 2026, depois de a Segunda Turma referendar as prisões, o relator apreciou os pedidos de revogação apresentados por quatro investigados.", 
      ents=["André Mendonça"]),
 dict(proc="PET 16019", seq=32, pag=6, 
      q="Em seu parecer nos autos, o Ministério Público Federal", ate="(e-Doc. 30).", 
      t="A Procuradoria-Geral da República apoia o bloqueio", 
      ctx="Antes de decidir, o relator abriu vista à Procuradoria-Geral da República, que se manifestou a favor das medidas pedidas pela Polícia Federal.", 
      ents=["André Mendonça"]),
 dict(proc="PET 16019", seq=32, pag=36, 
      q="A constrição patrimonial pretendida possui natureza estritamente assecuratória", ate="da execução de eventual condenação futura.", 
      t="O relator ressalva que o bloqueio não antecipa condenação", 
      ctx="A decisão registra o limite da medida: bloquear bens não equivale a declarar culpa de quem é investigado.", 
      ents=["André Mendonça"]),
 dict(proc="PET 16019", seq=32, pag=38, 
      q="Dessa forma, considerando a robustez do quadro indiciário", ate="em consonância com a manifestação do MPF nos autos.", 
      t="O relator defere o bloqueio pedido pela Polícia Federal", 
      ctx="É a conclusão da decisão de 13 de maio de 2026, que atingiu sete investigados, com limites de R$ 1,8 milhão para três deles e de R$ 9,6 milhões para os outros quatro.", 
      ents=["André Mendonça"]),
 dict(proc="PET 16019", seq=32, pag=41, 
      q="Para a operacionalização da medida de bloqueio dos imóveis", ate="para a operacionalização do bloqueio nos sistemas existentes.", 
      t="O relator manda cumprir o bloqueio pelos sistemas CNIB e equivalentes", 
      ctx="A decisão detalha como o gabinete deve executar a ordem e reafirma que o teto de cada investigado é o valor fixado para ele.", 
      ents=["André Mendonça"]),
 dict(proc="PET 16019", seq=81, pag=1, 
      q="Defiro o pedido, a fim de autorizar o acesso temporário aos advogados", ate="mediante habilitação nos autos.", 
      t="O relator abre os autos sigilosos às defesas", 
      ctx="Em 12 de junho de 2026 o relator autorizou advogados a consultar o processo, nos limites da Súmula Vinculante 14, e estendeu a regra às defesas dos demais investigados.", 
      ents=["André Mendonça"]),
 dict(proc="PET 16662", seq=26, pag=21, 
      q="E o risco de que continuem sendo produzidos", ate="impõe providência judicial imediata.", 
      t="O relator diz por que agiu de imediato", 
      ctx="A decisão de 8 de setembro de 2026 trata de relatórios de inteligência da Polícia Federal sobre a atuação de autoridades e afirma haver risco de que novos documentos do mesmo tipo sejam produzidos.", 
      ents=["André Mendonça"]),
 dict(proc="PET 16662", seq=26, pag=32, 
      q="determino: (i) o afastamento preventivo dos senhores", ate="Diretor de Inteligência Policial da Polícia Federal, respectivamente;", 
      t="O relator afasta o diretor-geral e o diretor de inteligência da PF", 
      ctx="É o comando central da liminar de 8 de setembro de 2026, que também mandou a Corregedoria da PF abrir apuração e suspendeu a produção de novos relatórios de inteligência sobre atos de magistrados, advogados públicos e policiais.", 
      ents=["André Mendonça", "Andrei Augusto Passos Rodrigues"]),
 dict(proc="PET 16662", seq=45, pag=1, 
      q="Após o voto do Ministro André Mendonça (Relator) que referendava", ate="pediu vista dos autos o Ministro Gilmar Mendes.", 
      t="A Segunda Turma interrompe o referendo com pedido de vista", 
      ctx="Na sessão virtual extraordinária de 8 de setembro de 2026, três ministros já haviam acompanhado o relator quando o julgamento foi suspenso.", 
      ents=["André Mendonça", "Gilmar Mendes", "Nunes Marques"]),
 dict(proc="PET 16662", seq=46, pag=4, 
      q="No caso ora em apreciação, na esteira dos fundamentos que externei", ate="lesão à ordem pública e à integridade deste Tribunal.", 
      t="A Presidência suspende a liminar sem entrar no mérito", 
      ctx="Decisão do Presidente do Supremo, de 9 de setembro de 2026, na Suspensão de Liminar 1.946, pedida pela União contra a decisão do relator.", 
      ents=[]),
 dict(proc="PET 16662", seq=48, pag=10, 
      q="No tocante à Pet 16662, de relatoria do Ministro André Mendonça", ate="para o dia 15 de setembro de 2026, às 10 horas.", 
      t="A Presidência convoca sessão plenária extraordinária", 
      ctx="No mesmo 9 de setembro de 2026, ao suspender e sobrestar o processo, o Presidente levou o caso ao Plenário do Supremo.", 
      ents=["André Mendonça"]),
]
