# -*- coding: utf-8 -*-
"""Tabela de tradução PT→EN para docs/app.js → docs/app.en.js.
Cada item: (trecho exato em app.js, tradução[, "all"]).  Sem "all", o trecho
tem de ocorrer exatamente UMA vez; com "all", todas as ocorrências são trocadas.
Se um trecho não for encontrado, o build falha: é o sinal de que app.js mudou
e a tradução precisa de revisão."""

JS = [
 # --- excertos (v0.4) ---
 ('Esta crônica é sobre o processo <b>${pr}</b>. <button class="btn small" data-goproc2="${pr}">Abrir a página do processo</button>',
  'This chronicle is about proceeding <b>${pr}</b>. <button class="btn small" data-goproc2="${pr}">Open the proceeding page</button>'),
 ('>ler um trecho</button>', '>read a passage</button>'),
 ('load("rastro.json"),load("resumos.json"),load("excertos.json")', 'load("rastro.json"),load("resumos_en.json"),load("excertos.json")'),
 ('<h3>Nas palavras da decisão</h3><p class="muted small">Trechos literais dos atos assinados pelo relator e pela Procuradoria, recortados do próprio documento. Não citamos representação da polícia nem petição de defesa.</p>',
  '<h3>In the ruling\'s own words</h3><p class="muted small">Verbatim passages from acts signed by the rapporteur and by the Prosecutor General, cut from the document itself and kept in the original Portuguese. We do not quote police filings or defence petitions.</p>'),
 ('<h4 style="margin-top:20px">Citado nas decisões</h4><p class="muted small">Trechos literais de atos do juízo em que este nome aparece. Ser citado numa decisão não conclui nada.</p>',
  '<h4 style="margin-top:20px">Named in the rulings</h4><p class="muted small">Verbatim passages, in the original Portuguese, from court acts where this name appears. Being named in a ruling settles nothing.</p>'),
 ('` · <b>${excDe(p.processo).length} excertos</b>`', '` · <b>${excDe(p.processo).length} passages</b>`'),

 # --- processos: resumo em linguagem natural e rastro documental (v0.3) ---
 ('const MES=["janeiro","fevereiro","março","abril","maio","junho","julho","agosto","setembro","outubro","novembro","dezembro"];',
  'const MES=["January","February","March","April","May","June","July","August","September","October","November","December"];'),
 ('const dataLonga=d=>{const[y,m,x]=d.split("-");return `${+x} de ${MES[+m-1]} de ${y}`;};',
  'const dataLonga=d=>{const[y,m,x]=d.split("-");return `${MES[+m-1]} ${+x}, ${y}`;};'),
 ('const mesDe=d=>{const[y,m]=d.split("-");return `${MES[+m-1]} de ${y}`;};',
  'const mesDe=d=>{const[y,m]=d.split("-");return `${MES[+m-1]} ${y}`;};'),
 ('return `${mesDe(ini)} — ${mesDe(fim)}`;', 'return `${mesDe(ini)} — ${mesDe(fim)}`;'),
 ('["a Polícia Federal apresenta a representação","representações da Polícia Federal"]',
  '["the Federal Police files its petition","Federal Police petitions"]'),
 ('["a Procuradoria-Geral da República apresenta manifestação","manifestações da Procuradoria"]',
  '["the Prosecutor General\'s Office files an opinion","opinions from the Prosecutor General"]'),
 ('["uma defesa apresenta petição inicial","petições iniciais de defesas"]',
  '["a defence files an opening petition","opening petitions from defences"]'),
 ('["o Banco Central apresenta informações","informações do Banco Central"]',
  '["the Central Bank files information","filings from the Central Bank"]'),
 ('["petição inicial","petições iniciais"]', '["opening petition","opening petitions"]'),
 ('["o relator aprecia um pedido liminar","decisões liminares"]', '["the rapporteur rules on an injunction request","injunction rulings"]'),
 ('["o relator profere decisão final","decisões finais"]', '["the rapporteur issues a final ruling","final rulings"]'),
 ('["o relator decide","decisões do relator"]', '["the rapporteur rules","rulings by the rapporteur"]'),
 ('["o relator despacha","despachos do relator"]', '["the rapporteur issues an order","orders by the rapporteur"]'),
 ('["os autos vão à Procuradoria-Geral da República","remessas à Procuradoria"]',
  '["the file goes to the Prosecutor General\'s Office","referrals to the Prosecutor General"]'),
 ('["a Procuradoria-Geral da República se manifesta","manifestações da Procuradoria"]',
  '["the Prosecutor General\'s Office weighs in","opinions from the Prosecutor General"]', "all"),
 ('["a Polícia Federal peticiona","petições da Polícia Federal"]', '["the Federal Police files a petition","petitions from the Federal Police"]'),
 ('["o Banco Central responde","respostas do Banco Central"]', '["the Central Bank answers","answers from the Central Bank"]'),
 ('const o=orgDe(st); return [o?`${o} responde ao ofício`:"um ofício é respondido","respostas a ofícios"];',
  'const o=orgDe(st); return [o?`${o} answers the court order`:"an institution answers the court order","answers to court orders"];'),
 ('["uma defesa peticiona","petições de defesas"]', '["a defence files a petition","petitions from defences"]'),
 ('return [st?`junta-se aos autos: ${acentua(st).toLowerCase()}`:"petição juntada aos autos","petições juntadas"];',
  'return [st?`added to the file: ${acentua(st).toLowerCase()}`:"a petition is added to the file","petitions added to the file"];'),
 ('["ofício do relator determinando diligências","ofícios do relator determinando diligências"]',
  '["a court order from the rapporteur requiring steps to be taken","court orders from the rapporteur requiring steps to be taken"]'),
 ('["mandado de busca e apreensão expedido","mandados de busca e apreensão expedidos"]',
  '["a search warrant is issued","search warrants are issued"]'),
 ('["mandado de prisão expedido","mandados de prisão expedidos"]', '["an arrest warrant is issued","arrest warrants are issued"]'),
 ('["mandado de intimação expedido","mandados de intimação expedidos"]', '["a summons is issued","summonses are issued"]'),
 ('["ofício comunicando a decisão","ofícios comunicando a decisão"]', '["a court order conveying the ruling","court orders conveying the ruling"]'),
 ('["certidão nos autos","certidões nos autos"]', '["a certificate is filed","certificates are filed"]'),
 ('["comunicação assinada pelo relator","comunicações assinadas pelo relator"]',
  '["a signed communication from the rapporteur","signed communications from the rapporteur"]'),
 ('["o processo é distribuído ao relator","certidões de distribuição"]', '["the case is assigned to the rapporteur","assignment certificates"]'),
 ('["a secretaria certifica que o prazo passou sem manifestação","certidões de prazo vencido"]',
  '["the registry certifies that the deadline lapsed with no filing","certificates of lapsed deadlines"]'),
 ('["a autuação é retificada","retificações de autuação"]', '["the case record is corrected","corrections to the case record"]'),
 ('["a decisão transita em julgado","certidões de trânsito em julgado"]', '["the ruling becomes final","certificates that the ruling became final"]'),
 ('["a secretaria certifica um ato","certidões da secretaria"]', '["the registry certifies a step","registry certificates"]'),
 ('["certidão de julgamento do colegiado","certidões de julgamento"]', '["a panel judgment certificate","panel judgment certificates"]'),
 ('["intimação expedida","intimações expedidas"]', '["a summons is served","summonses are served"]'),
 ('["mandado expedido","mandados expedidos"]', '["a warrant is issued","warrants are issued"]'),
 ('["auto de busca e apreensão juntado","autos de busca e apreensão"]', '["a search and seizure record is filed","search and seizure records"]'),
 ('["peça de prisão preventiva juntada","peças de prisão preventiva"]', '["a pre-trial detention filing","pre-trial detention filings"]'),
 ('["peça de sequestro de bens juntada","peças de sequestro de bens"]', '["an asset freeze filing","asset freeze filings"]'),
 ('["pedido de restituição de coisas apreendidas","pedidos de restituição"]',
  '["a request for the return of seized property","requests for the return of seized property"]'),
 ('["os autos são disponibilizados à autoridade policial","termos de disponibilização dos autos"]',
  '["the file is made available to the police","records of the file being made available"]'),
 ('["comunicação de outro juízo","comunicações de outros juízos"]', '["a communication from another court","communications from other courts"]'),
 ('["peça do inquérito juntada","peças do inquérito"]', '["an investigation filing","investigation filings"]'),
 ('["informação juntada aos autos","informações juntadas"]', '["information is added to the file","information added to the file"]'),
 ('["pedido de reconsideração","pedidos de reconsideração"]', '["a motion to reconsider","motions to reconsider"]'),
 ('["apresentação de defesa","apresentações de defesa"]', '["a defence is filed","defences are filed"]'),
 ('["pedido de ingresso como interessado","pedidos de ingresso"]', '["a request to join as an interested party","requests to join as interested parties"]'),
 ('["pedido de juntada de documentos","pedidos de juntada"]', '["a request to file documents","requests to file documents"]'),
 ('["acórdão publicado","acórdãos publicados"]', '["a panel decision is published","panel decisions published"]'),
 ('return [tipo(t).toLowerCase()+" juntado",tipo(t).toLowerCase()];', 'return [tipo(t).toLowerCase()+" filed",tipo(t).toLowerCase()];'),
 ('const pg=pags>=3?`${fmt(pags)} pág.`:"";', 'const pg=pags>=3?`${fmt(pags)} pp.`:"";'),
 ('<p class="eyebrow">${proc} · ${esc(R.t)}</p>', '<p class="eyebrow">${proc} · ${esc(R.t)}</p>'),
 ('<span><b>${fmt(p.pdfs)}</b> peças</span><span><b>${fmt(p.pages)}</b> páginas</span><span><b>${n}</b> movimentos</span>',
  '<span><b>${fmt(p.pdfs)}</b> filings</span><span><b>${fmt(p.pages)}</b> pages</span><span><b>${n}</b> steps</span>'),
 ('Há uma série de crônicas sobre este processo. <button class="btn small" data-cr="${esc(R.s)}">Ler a série</button>',
  'There is a chronicle series on this proceeding. <button class="btn small" data-cr="${esc(R.s)}">Read the series</button>'),
 ('<h3>Os momentos que importam</h3>', '<h3>The moments that matter</h3>'),
 ('<h3>O rastro, dia a dia</h3>', '<h3>The paper trail, day by day</h3>'),
 ('Cada linha é uma peça dos autos, descrita pelo que ela é. O <em>seq</em> é o número da peça no processo e o começo do nome do arquivo no pacote público do STF. Peças iguais no mesmo dia aparecem juntas.',
  'Each line is one filing, described by what it is. The <em>seq</em> is the filing number within the proceeding and the start of the file name in the Supreme Court\'s public package. Identical filings on the same day are grouped.'),
 ('>mostrar o rastro inteiro<', '>show the whole trail<'),
 ('<h3>Quem mais aparece</h3><div class="tops">', '<h3>Who appears most</h3><div class="tops">'),
 ('Contagem de peças narrativas em que o nome aparece. Aparecer muito não diz o que a pessoa fez.',
  'Number of narrative filings the name appears in. Appearing often says nothing about what the person did.'),
 ('<h3>Este processo cita</h3>', '<h3>This proceeding cites</h3>'),
 ('data-graph="${esc(proc)}">Ver só este processo no grafo</button>', 'data-graph="${esc(proc)}">See only this proceeding in the graph</button>'),
 ('data-mmp="${esc(proc)}">Mapa mental</button>', 'data-mmp="${esc(proc)}">Mind map</button>'),
 ('data-tl="${esc(proc)}">Linha do tempo</button>', 'data-tl="${esc(proc)}">Timeline</button>'),
 ('>← todos os processos<', '>← all proceedings<'),
 ('Mostrando só <b>${esc(byId.get(selected).label)}</b> e as ligações diretas. <button class="lnk" id="focusAll">ver o grafo inteiro</button>',
  'Showing only <b>${esc(byId.get(selected).label)}</b> and its direct links. <button class="lnk" id="focusAll">see the whole graph</button>'),

 ('toLocaleString("pt-BR")', 'toLocaleString("en-US")'),
 ('{pessoa:"pessoa",empresa:"empresa",autoridade:"autoridade",advogado:"advogado",pseudo:"pseudonimizado"}',
  '{pessoa:"person",empresa:"company",autoridade:"official",advogado:"lawyer",pseudo:"pseudonymized"}'),
 ('{pessoa:"Pessoas",empresa:"Empresas",autoridade:"Autoridades",advogado:"Advogados",pseudo:"Pseudonimizados"}',
  '{pessoa:"People",empresa:"Companies",autoridade:"Officials",advogado:"Lawyers",pseudo:"Pseudonymized"}'),
 ('const TIPO={"Decisao monocratica":"Decisão monocrática","Peticao":"Petição","Peticao inicial":"Petição inicial","Despacho":"Despacho","Busca e apreensao":"Busca e apreensão","Prisao preventiva":"Prisão preventiva","Inquerito":"Inquérito","Sequestro":"Sequestro","Manifestacao":"Manifestação","Manifestacao da PGR":"Manifestação da PGR","Outras pecas":"Outras peças","Vista a PGR":"Vista à PGR","Mandado":"Mandado","Restituicao de coisas apreendidas":"Restituição de coisas apreendidas","Certidao de julgamento":"Certidão de julgamento","Documentos comprobatorios":"Documentos comprobatórios","Documento comprobatorio":"Documento comprobatório","Recibo de peticao eletronica":"Recibo de petição eletrônica","Comunicacao assinada":"Comunicação assinada","Procuracao":"Procuração","Intimacao":"Intimação","Certidao":"Certidão","Mandado de intimacao":"Mandado de intimação","Documentos de identificacao":"Documentos de identificação","Malote Digital":"Malote digital","Termo de disponibilizacao de autos":"Termo de disponibilização","Aviso de recebimento":"Aviso de recebimento"};',
  'const TIPO={"Decisao monocratica":"Single-justice ruling","Peticao":"Petition","Peticao inicial":"Initial petition","Despacho":"Procedural order","Busca e apreensao":"Search and seizure","Prisao preventiva":"Pre-trial detention","Inquerito":"Inquiry","Sequestro":"Asset freeze","Manifestacao":"Submission","Manifestacao da PGR":"Prosecutor General\'s submission","Outras pecas":"Other filings","Vista a PGR":"Referral to the Prosecutor General","Mandado":"Warrant","Restituicao de coisas apreendidas":"Return of seized property","Certidao de julgamento":"Certificate of judgment","Documentos comprobatorios":"Supporting documents","Documento comprobatorio":"Supporting document","Recibo de peticao eletronica":"E-filing receipt","Comunicacao assinada":"Signed communication","Procuracao":"Power of attorney","Intimacao":"Notice","Certidao":"Certificate","Mandado de intimacao":"Writ of notice","Documentos de identificacao":"Identity documents","Malote Digital":"Digital courier","Termo de disponibilizacao de autos":"Record-release note","Aviso de recebimento":"Return receipt"};'),
 ('"graph.json","entities.json","processos.json","crossrefs.json","timeline.json","cnpjs.json","meta.json","wiki.json"',
  '"graph.json","entities.json","processos.json","crossrefs.json","timeline.json","cnpjs.json","meta.json","wiki_en.json"'),
 ('const views=["inicio","tour","grafo","mapa","personagens","rede","processos","tempo","cronicas","metodo","avisos"];',
  'const views=["inicio","tour","grafo","mapa","personagens","whoswho","primer","rede","processos","tempo","cronicas","metodo","avisos"];'),
 ('"Menos filtros ▴":"Filtros ▾"', '"Fewer filters ▴":"Filters ▾"'),
 ('open?"Ajustes ▴":"Ajustes ▾"', 'open?"Settings ▴":"Settings ▾"'),
 ('[[META.corpus.paginas,"páginas"],[META.corpus.pdfs,"peças (PDF)"],[META.corpus.processos.length,"processos"],[META.grafo.nos,"nós no grafo"],[META.grafo.arestas,"relações"],[META.grafo.pseudonimizados,"pessoas pseudonimizadas"],[META.grafo.docs_narrativos||0,"peças narrativas lidas para o grafo"]]',
  '[[META.corpus.paginas,"pages"],[META.corpus.pdfs,"filings (PDF)"],[META.corpus.processos.length,"proceedings"],[META.grafo.nos,"nodes in the graph"],[META.grafo.arestas,"relations"],[META.grafo.pseudonimizados,"pseudonymized people"],[META.grafo.docs_narrativos||0,"narrative filings read for the graph"]]'),
 ('`Dados gerados em ${META.gerado_em}. Pacote de origem: ${META.fonte.pacote}, ${fmt(META.fonte.bytes)} bytes, modificado em ${META.fonte.last_modified}.`',
  '`Data generated on ${META.gerado_em}. Source package: ${META.fonte.pacote}, ${fmt(META.fonte.bytes)} bytes, last modified ${META.fonte.last_modified}.`'),
 ('aria-label="Fechar"', 'aria-label="Close"', "all"),
 # painel de aresta
 ('Natureza da ligação: os dois nomes aparecem <b>na mesma página</b> de ${w} peça(s) narrativa(s), em ${pr} processo(s). Isso é coocorrência documental, não prova de relação; a lista abaixo diz onde ler.',
  'Nature of the link: both names appear <b>on the same page</b> of ${w} narrative filing(s), across ${pr} proceeding(s). That is documentary co-occurrence, not proof of a relationship; the list below says where to read.'),
 ('<div class="kv"><div><b>${w}</b><span>peças em comum</span></div><div><b>${pr}</b><span>processos</span></div><div><b>${Object.keys(d.tipos).length}</b><span>tipos de peça</span></div></div>',
  '<div class="kv"><div><b>${w}</b><span>filings in common</span></div><div><b>${pr}</b><span>proceedings</span></div><div><b>${Object.keys(d.tipos).length}</b><span>filing types</span></div></div>'),
 ('<h4>Por tipo de peça</h4>', '<h4>By filing type</h4>'),
 ("<span class='muted'>sem detalhe</span>", "<span class='muted'>no detail</span>"),
 ('<h4>Onde conferir (páginas em que ambos aparecem)</h4><table><tr><th>processo</th><th>seq</th><th>peça</th><th>pág.</th><th>×</th></tr>',
  '<h4>Where to check (pages where both appear)</h4><table><tr><th>proceeding</th><th>seq</th><th>filing</th><th>p.</th><th>×</th></tr>'),
 ('<span class="muted">${w} peça(s) em ${pr} processo(s)</span>${d?"<br>"+tipoSummary(d):""}<br><span class="muted">clique para ver onde</span>',
  '<span class="muted">${w} filing(s) in ${pr} proceeding(s)</span>${d?"<br>"+tipoSummary(d):""}<br><span class="muted">click to see where</span>'),
 ('${n.docs} peças · ${n.procs} processos · ${graph.degree(node)} ligações', '${n.docs} filings · ${n.procs} proceedings · ${graph.degree(node)} links'),
 ('<span>datas citadas junto ao nome</span>', '<span>dates cited alongside the name</span>'),
 # painel do nó
 ('<span class="muted">nome omitido por política</span>', '<span class="muted">name withheld by policy</span>'),
 ('<div class="kv"><div><b>${fmt(n.docs)}</b><span>peças</span></div><div><b>${n.procs}</b><span>processos</span></div><div><b>${fmt(n.mentions)}</b><span>menções</span></div></div>',
  '<div class="kv"><div><b>${fmt(n.docs)}</b><span>filings</span></div><div><b>${n.procs}</b><span>proceedings</span></div><div><b>${fmt(n.mentions)}</b><span>mentions</span></div></div>'),
 ('title="Métricas do grafo completo. Pontes: intermediação (×1000). Influência: PageRank (×1000). Agrupamento: quanto os vizinhos se ligam entre si. Fora do núcleo: parcela das ligações que sai da comunidade."',
  'title="Metrics of the full graph. Bridges: betweenness (×1000). Influence: PageRank (×1000). Clustering: how much a node\'s neighbours link to one another. Outside the cluster: share of the links that leave the community."'),
 ('<span>pontes</span></div><div><b>${n.pr??0}</b><span>influência</span></div><div><b>${n.cc??0}</b><span>agrupam.</span></div><div><b>${Math.round((n.br||0)*100)}%</b><span>fora do núcleo</span></div><div><b>${n.jud||0}</b><span>em decisões</span></div>',
  '<span>bridges</span></div><div><b>${n.pr??0}</b><span>influence</span></div><div><b>${n.cc??0}</b><span>clustering</span></div><div><b>${Math.round((n.br||0)*100)}%</b><span>outside cluster</span></div><div><b>${n.jud||0}</b><span>in rulings</span></div>'),
 ('`Datas citadas junto ao nome: ${n.m0} a ${n.m1}`', '`Dates cited alongside the name: ${n.m0} to ${n.m1}`'),
 ('núcleo <b style="color:${COMM[n.c%COMM.length]}">', 'cluster <b style="color:${COMM[n.c%COMM.length]}">'),
 ('data-wiki="${id}">Ficha</button>', 'data-wiki="${id}">Profile</button>'),
 ('>Mapa mental</button>', '>Mind map</button>', "all"),
 ('>Só a vizinhança</button>', '>Neighbourhood only</button>'),
 ('>Ocultar nó</button>', '>Hide node</button>'),
 ('<h4>Presença por processo</h4>', '<h4>Presence by proceeding</h4>', "all"),
 ('<h4>Aparece junto de</h4>', '<h4>Appears alongside</h4>'),
 ('title="Vizinhos com ao menos 3 peças em comum, ordenados por peças em comum × log da especificidade (lift)">Ligações mais específicas</h4>',
  'title="Neighbours with at least 3 filings in common, ranked by filings in common × log of specificity (lift)">Most specific links</h4>'),
 ('title="${w} peças em comum · ${l}× o esperado"', 'title="${w} filings in common · ${l}× the expected"'),
 ("<span class='muted'>nenhuma com 3+ peças em comum</span>", "<span class='muted'>none with 3+ filings in common</span>"),
 ('<h4>Onde conferir</h4><table><tr><th>processo</th><th>seq</th><th>peça</th><th>pág.</th></tr>',
  '<h4>Where to check</h4><table><tr><th>proceeding</th><th>seq</th><th>filing</th><th>p.</th></tr>', "all"),
 ('"seq" é o número que inicia o nome do arquivo na pasta do processo dentro do <a href="${STF}" target="_blank" rel="noopener">pacote público do STF</a>. Coocorrência na mesma página não prova relação; é um ponto de partida para leitura.',
  '"seq" is the number that begins the file name inside the proceeding\'s folder in the <a href="${STF}" target="_blank" rel="noopener">STF\'s public package</a>. Co-occurrence on the same page does not prove a relationship; it is a starting point for reading.'),
 ('<span class="muted">${n.docs} peças</span></li>', '<span class="muted">${n.docs} filings</span></li>'),
 # caminho / em comum
 ('const what=pickKind==="common"?"Em comum: ":"Caminho: "; h.textContent=on?what+(pathA?`A = ${byId.get(pathA).label}. Agora clique (ou busque) o nó B.`:"clique (ou busque) o nó A."):"";',
  'const what=pickKind==="common"?"In common: ":"Path: "; h.textContent=on?what+(pathA?`A = ${byId.get(pathA).label}. Now click (or search) node B.`:"click (or search) node A."):"";'),
 ('alert("Layout ao vivo indisponível nesta build.")', 'alert("Live layout is unavailable in this build.")'),
 ('(pickKind==="common"?"Em comum: ":"Caminho: ")+`A = ${byId.get(id).label}. Agora clique (ou busque) o nó B.`',
  '(pickKind==="common"?"In common: ":"Path: ")+`A = ${byId.get(id).label}. Now click (or search) node B.`'),
 ('"Sem caminho entre os dois no grafo."', '"No path between the two in the graph."'),
 ('`Caminho em ${path.length-1} passo(s): ', '`Path in ${path.length-1} step(s): '),
 ('>limpar</button>', '>clear</button>', "all"),
 # mapa mental
 ('label:"Processos",color:css("--cyan")', 'label:"Proceedings",color:css("--cyan")'),
 ('sub:`${fmt(p.pages)} pág.`', 'sub:`${fmt(p.pages)} pp.`'),
 ('sub:`${pe[1]} peças`', 'sub:`${pe[1]} filings`'),
 ('sub:`${w} peças em comum`', 'sub:`${w} filings in common`'),
 ('mm.mode==="caso"?"Operação Compliance Zero"', 'mm.mode==="caso"?"Operation Compliance Zero"'),
 ('>sem ${faltam.join(", ")} nas peças narrativas deste processo</text>', '>no ${faltam.join(", ")} in the narrative filings of this proceeding</text>'),
 ('<span class="muted">${w} peça(s) em comum com ${byId.get(mm.center).label}</span>${d?"<br>"+tipoSummary(d):""}<br><span class="muted">clique para recentrar</span>',
  '<span class="muted">${w} filing(s) in common with ${byId.get(mm.center).label}</span>${d?"<br>"+tipoSummary(d):""}<br><span class="muted">click to recentre</span>'),
 ('<span class="muted">${pe?pe[1]:0} peça(s) em ${mm.proc} · ${n.docs} no total</span>', '<span class="muted">${pe?pe[1]:0} filing(s) in ${mm.proc} · ${n.docs} in total</span>'),
 ('<span class="muted">${fmt(pr.pdfs)} peças · ${fmt(pr.pages)} páginas</span>', '<span class="muted">${fmt(pr.pdfs)} filings · ${fmt(pr.pages)} pages</span>'),
 ('`<span>anteriores:</span> `', '`<span>previous:</span> `'),
 # processos
 ('p.startsWith("INQ")?"inquérito":p.startsWith("RCL")?"reclamação":"petição"', 'p.startsWith("INQ")?"inquiry":p.startsWith("RCL")?"complaint":"petition"'),
 ('title="${r} cita ${c}: ${n} peças"', 'title="${r} cites ${c}: ${n} filings"'),
 # linha do tempo
 ('`<b>${a} a ${b}</b> · ${fmt(tot)} datas citadas · ', '`<b>${a} to ${b}</b> · ${fmt(tot)} dates cited · '),
 ('>ver ligações deste período no grafo</button>', '>see this period\'s links in the graph</button>'),
 ('${fmt(val[ms.indexOf(k)])} datas citadas', '${fmt(val[ms.indexOf(k)])} dates cited'),
 ('Adicione até cinco personagens para comparar.', 'Add up to five names to compare.'),
 ('<div class="pk">pico ${pk}<br>${fmt(mx)} datas</div>', '<div class="pk">peak ${pk}<br>${fmt(mx)} dates</div>'),
 # tour
 ('{t:"O acervo em 30 segundos",b:`Em 10 de setembro de 2026 o relator, ministro <strong>André Mendonça</strong>, retirou o sigilo da Petição 15.556 e de quatorze procedimentos ligados à <strong>Operação Compliance Zero</strong>, a pedido da presidência do STF. No dia seguinte o Tribunal publicou tudo: <strong>${fmt(META.corpus.pdfs)} peças</strong>, <strong>${fmt(META.corpus.paginas)} páginas</strong>. Ninguém lê isso na íntegra. Este site extrai do texto quem aparece, em que papel e ao lado de quem, e devolve cada afirmação à sua página de origem.`,\n  tip:"O que este site é: um índice de relações com fonte. O que não é: cópia dos documentos, lista de CPFs, ou conclusão sobre culpa de quem quer que seja."',
  '{t:"The archive in 30 seconds",b:`On 10 September 2026 the reporting justice, <strong>André Mendonça</strong>, lifted the seal on Petition 15.556 and on fourteen proceedings tied to <strong>Operation Compliance Zero</strong>, at the request of the Court\'s presidency. The next day the Court published everything: <strong>${fmt(META.corpus.pdfs)} filings</strong>, <strong>${fmt(META.corpus.paginas)} pages</strong>. Nobody reads that in full. This site pulls out of the text who appears, in which role and alongside whom, and sends every statement back to the page it came from.`,\n  tip:"What this site is: a sourced index of relationships. What it is not: a copy of the documents, a list of taxpayer numbers, or a conclusion about anyone\'s guilt."'),
 ('{t:"Quinze processos, um caso",b:`O material não é um processo só. São inquéritos (INQ), petições (PET) e uma reclamação (RCL) que se citam mutuamente. Os volumes são muito desiguais: a <strong>${biggestProc.processo}</strong> sozinha tem ${fmt(biggestProc.pages)} páginas, quase tudo mídia de DVD com autos de processos federais anexados como prova. No mapa abaixo, o tamanho do círculo é o número de páginas. Clique num processo para ver quem domina cada um.`,\n  tip:"Volume não é importância. A peça decisiva de um caso pode ter cinco páginas."',
  '{t:"Fifteen proceedings, one case",b:`The material is not a single case file. It is a set of inquiries (INQ), petitions (PET) and one constitutional complaint (RCL) that cite one another. The volumes are wildly uneven: <strong>${biggestProc.processo}</strong> alone runs to ${fmt(biggestProc.pages)} pages, almost all of it DVD media with the records of federal lawsuits attached as evidence. In the map below, the size of the circle is the page count. Click a proceeding to see who dominates each one.`,\n  tip:"Volume is not importance. The decisive filing in a case can be five pages long."'),
 ('{t:"Quem é quem: quatro papéis",b:`Cada nó recebe um papel inferido do próprio texto. <strong>Empresa</strong>: termo societário no nome. <strong>Autoridade</strong>: cargo no contexto, ou assinatura em todas as páginas de uma peça longa. <strong>Advogado</strong>: remetente do recibo de petição eletrônica, ou inscrição profissional junto ao nome. <strong>Pessoa</strong>: o resto. Advogados ficam ocultos por padrão: assinam juntos as mesmas petições e formam blocos densos que só dizem "trabalham no mesmo escritório".`,\n  tip:"Ligue o filtro Advogados na barra do grafo para ver o bloco denso aparecer. Depois desligue."',
  '{t:"Who is who: four roles",b:`Each node gets a role inferred from the text itself. <strong>Company</strong>: a corporate term in the name. <strong>Official</strong>: a public office in context, or a signature on every page of a long filing. <strong>Lawyer</strong>: sender of the e-filing receipt, or a bar registration next to the name. <strong>Person</strong>: everyone else. Lawyers are hidden by default: they co-sign the same petitions and form dense blocks that only say "they work at the same firm".`,\n  tip:"Switch on the Lawyers filter in the graph bar to watch the dense block appear. Then switch it off."'),
 ('{t:"O centro do grafo",b:`O nó com mais conexões ponderadas entre as pessoas é <strong>${centerPessoa.label}</strong>: ${centerPessoa.procs} dos 15 processos, ${fmt(centerPessoa.docs)} peças narrativas. A ficha ao lado lista com quem ele mais divide páginas. A empresa mais próxima é <strong>${byId.get(strongest(centerPessoa.id,"empresa")[0]).label}</strong>, com ${strongest(centerPessoa.id,"empresa")[1]} peças em comum.`,\n  tip:"Passe o mouse sobre qualquer nó para acender só a vizinhança dele. Clique para trocar a ficha."',
  '{t:"The centre of the graph",b:`The node with the most weighted connections among people is <strong>${centerPessoa.label}</strong>: ${centerPessoa.procs} of the 15 proceedings, ${fmt(centerPessoa.docs)} narrative filings. The panel alongside lists who shares pages with that name most often. The closest company is <strong>${byId.get(strongest(centerPessoa.id,"empresa")[0]).label}</strong>, with ${strongest(centerPessoa.id,"empresa")[1]} filings in common.`,\n  tip:"Hover over any node to light up only its neighbourhood. Click to switch the panel."'),
 ('{t:"Siga as empresas",b:`Filtrar só empresas revela a espinha dorsal societária do caso: bancos, gestoras, holdings e veículos de investimento que se repetem entre processos diferentes. Uma empresa presente em muitos processos é um fio condutor. Ao todo, <strong>${empresas5}</strong> empresas aparecem em cinco ou mais processos.`,\n  tip:"Recorrência entre processos é sinal. Volume dentro de um único processo, quase sempre, é só um anexo grande."',
  '{t:"Follow the companies",b:`Filtering down to companies reveals the corporate backbone of the case: banks, asset managers, holding companies and investment vehicles that recur across different proceedings. A company present in many proceedings is a thread to pull. In all, <strong>${empresas5}</strong> companies appear in five or more proceedings.`,\n  tip:"Recurrence across proceedings is a signal. Volume inside a single proceeding is, almost always, just a large exhibit."'),
 ('{t:"Caminho entre dois nomes",b:`A pergunta clássica de apuração: <em>o que liga A a B?</em> O grafo responde com o caminho mais curto. O modo caminho já está armado com <strong>${centerPessoa.label}</strong> como A. Clique em <strong>${secondCluster.label}</strong>, que está em outro núcleo, para ver as pontes.`,\n  tip:"Os nós intermediários de um caminho são os que valem uma leitura de peça."',
  '{t:"Path between two names",b:`The classic investigative question: <em>what links A to B?</em> The graph answers with the shortest path. Path mode is already armed with <strong>${centerPessoa.label}</strong> as A. Click <strong>${secondCluster.label}</strong>, who sits in another cluster, to see the bridges.`,\n  tip:"The intermediate nodes of a path are the ones worth reading a filing for."'),
 ('{t:"O mapa mental",b:`Quando o grafo inteiro é demais, o mapa mental parte de um nome e abre os vínculos dele por categoria, ramo a ramo. Abaixo, <strong>${topEmpresa.label}</strong> no centro. Clique em qualquer ramo para recentrar nele e seguir o fio; os anteriores ficam como trilha de migalhas.`,\n  tip:"Use o mapa para uma apuração linear: de quem para quem. Use o grafo para ver o desenho de conjunto."',
  '{t:"The mind map",b:`When the whole graph is too much, the mind map starts from one name and opens its links by category, branch by branch. Below, <strong>${topEmpresa.label}</strong> sits at the centre. Click any branch to recentre on it and follow the thread; the earlier ones stay behind as a breadcrumb trail.`,\n  tip:"Use the map for a linear inquiry: from whom to whom. Use the graph to see the shape of the whole."'),
 ('{t:"Ler a fonte, e agora é com você",b:`Nada aqui é conclusão. Cada ficha tem uma tabela "Onde conferir" com <strong>processo, seq e página</strong>. O <em>seq</em> é o número sequencial da peça no processo, e é o início do nome do arquivo na pasta correspondente do pacote público do STF. Sugestões para começar: quem são as pontes entre núcleos? Que empresa aparece em processos que não se citam? Quais autoridades assinam peças em mais de um processo?`,\n  tip:"Encontrou erro de identificação ou de papel? Abra uma issue no repositório. A política é corrigir rápido."',
  '{t:"Read the source; now it is over to you",b:`Nothing here is a conclusion. Every profile has a "Where to check" table with <strong>proceeding, seq and page</strong>. The <em>seq</em> is the filing\'s sequence number within the proceeding, and it is the beginning of the file name in the matching folder of the STF\'s public package. Suggestions to start with: who are the bridges between clusters? Which company appears in proceedings that do not cite each other? Which officials sign filings in more than one proceeding?`,\n  tip:"Found an identification or role error? Open an issue in the repository. The policy is to fix it fast."'),
 ('`Passo ${i+1} de ${STEPS.length}`', '`Step ${i+1} of ${STEPS.length}`'),
 ('"Ir para o grafo →":"Próximo →"', '"Go to the graph →":"Next →"'),
 # personagens (wiki)
 ('>← todos os personagens</button>', '>← all profiles</button>'),
 ('<div class="kv" style="max-width:420px"><div><b>${fmt(p.docs)}</b><span>peças</span></div><div><b>${p.procs}</b><span>processos</span></div><div><b>${fmt(p.mentions)}</b><span>menções</span></div></div>',
  '<div class="kv" style="max-width:420px"><div><b>${fmt(p.docs)}</b><span>filings</span></div><div><b>${p.procs}</b><span>proceedings</span></div><div><b>${fmt(p.mentions)}</b><span>mentions</span></div></div>'),
 ('data-open="${p.id}">Abrir no grafo</button>', 'data-open="${p.id}">Open in the graph</button>'),
 ('rel="noopener">Ficha em Markdown</a>', 'rel="noopener">Profile in Markdown (Portuguese)</a><a class="btn ghost small" href="https://www.google.com/search?q=${encodeURIComponent(\'"\'+p.label+\'" "Banco Master"\')}" target="_blank" rel="noopener" title="Web search for this name; results are not part of the record">Search on Google</a>'),
 ('${roleBlock("pessoa","Aparece junto de · pessoas")}${roleBlock("empresa","Empresas")}${roleBlock("autoridade","Autoridades")}${roleBlock("advogado","Advogados")}',
  '${roleBlock("pessoa","Appears alongside · people")}${roleBlock("empresa","Companies")}${roleBlock("autoridade","Officials")}${roleBlock("advogado","Lawyers")}'),
 ('<h4>Tipos de peça</h4>', '<h4>Filing types</h4>', "all"),
 ('Ficha automática a partir dos dados públicos sanitizados. Coocorrência na mesma página não prova relação. Erros de identificação: abra uma issue.',
  'Automatic profile built from the sanitized public data. Co-occurrence on the same page does not prove a relationship. Identification errors: open an issue.'),
 ('<div class="m">${p.docs} peças · ${p.procs} processos${p.peak?` · pico ${p.peak}`:""}</div>', '<div class="m">${p.docs} filings · ${p.procs} proceedings${p.peak?` · peak ${p.peak}`:""}</div>'),
 ('`<p class="muted">Nada com esse filtro.</p>`', '`<p class="muted">Nothing matches this filter.</p>`'),
 # v0.2
 ('"só pseudonimizados"', '"pseudonymized only"'),
 ('<h4>Núcleos no recorte · ${rows.length}</h4>', '<h4>Clusters in this view · ${rows.length}</h4>'),
 ('<span class="muted">mostrar todos os núcleos</span>', '<span class="muted">show all clusters</span>'),
 ('"Espessura = especificidade (lift)":"Espessura = peças em comum"', '"Thickness = specificity (lift)":"Thickness = filings in common"', "all"),
 ('"Tamanho = "+({docs:"nº de peças",deg:"nº de ligações",bt:"pontes (no recorte)",pr:"influência (no recorte)",jud:"citações em decisões"})',
  '"Size = "+({docs:"no. of filings",deg:"no. of links",bt:"bridges (in view)",pr:"influence (in view)",jud:"citations in rulings"})', "all"),
 ('"Escolha dois nós diferentes."', '"Choose two different nodes."'),
 ('}: ${com.length} em comum <button', '}: ${com.length} in common <button'),
 ('Nomes que dividem página com <b>ambos</b>, respeitando os filtros atuais. Ordenados pela menor das duas ligações. Um nome aqui é um candidato a ponte entre os dois; a leitura das peças decide.',
  'Names that share a page with <b>both</b>, under the current filters. Ranked by the weaker of the two links. A name here is a candidate bridge between the two; reading the filings decides.'),
 ('<table><tr><th>nome</th><th>com A</th><th>com B</th></tr>', '<table><tr><th>name</th><th>with A</th><th>with B</th></tr>'),
 ("<td colspan=3 class='muted'>nenhum vizinho em comum com os filtros atuais</td>", "<td colspan=3 class='muted'>no neighbours in common under the current filters</td>"),
 ('[["nome","papel","nucleo","pecas","processos","mencoes","ligacoes_visiveis","pontes_x1000","influencia_x1000","agrupamento","fora_do_nucleo","em_decisoes","primeiro_mes","ultimo_mes"]]',
  '[["name","role","cluster","filings","proceedings","mentions","visible_links","bridges_x1000","influence_x1000","clustering","outside_cluster","in_rulings","first_month","last_month"]]'),
 ('dl("autos-abertos_nos.csv"', 'dl("autos-abertos_nodes.csv"'),
 ('[["a","b","pecas_em_comum","processos","especificidade_lift"]]', '[["a","b","filings_in_common","proceedings","specificity_lift"]]'),
 ('dl("autos-abertos_ligacoes.csv"', 'dl("autos-abertos_links.csv"'),
 ('ctx.fillText("autos-abertos · dados derivados de atos públicos do STF · coocorrência na mesma página não prova relação"',
  'ctx.fillText("autos-abertos · data derived from public STF records · co-occurrence on the same page does not prove a relationship"'),
 ('dl("autos-abertos_grafo.png"', 'dl("autos-abertos_graph.png"'),
 ('"copiado ✓"', '"copied ✓"', "all"),
 ('prompt("Copie o link:",url)', 'prompt("Copy the link:",url)', "all"),
 ('"copiar link"', '"copy link"', "all"),
 # análise de rede
 ('[[fmt(n),"nós no recorte"],[fmt(m),"ligações"],[nComm,"núcleos com 3+ nós"],[(dens*100).toFixed(1)+"%","densidade"],[med,"mediana de ligações"],[fmt(META.grafo.docs_narrativos||0),"peças narrativas"]]',
  '[[fmt(n),"nodes in view"],[fmt(m),"links"],[nComm,"clusters with 3+ nodes"],[(dens*100).toFixed(1)+"%","density"],[med,"median links"],[fmt(META.grafo.docs_narrativos||0),"narrative filings"]]'),
 ('`<p class="muted">Nenhum nó com esses filtros.</p>`', '`<p class="muted">No node matches these filters.</p>`'),
 ('<h3>Volume × ponte</h3><p class="sub">Horizontal: peças narrativas em que o nome aparece (escala log). Vertical: intermediação no recorte (raiz quadrada). Quem está no alto com pouco volume liga partes do grafo que de outro modo não se tocariam. Tamanho do ponto: influência (PageRank).</p>',
  '<h3>Volume × bridge</h3><p class="sub">Horizontal: narrative filings in which the name appears (log scale). Vertical: betweenness within this view (square root). Whoever sits high up with little volume connects parts of the graph that would otherwise not touch. Dot size: influence (PageRank).</p>'),
 ('text-anchor="end">peças (log) →</text><text transform="rotate(-90)" x="${-T}" y="12" text-anchor="end">pontes →</text>',
  'text-anchor="end">filings (log) →</text><text transform="rotate(-90)" x="${-T}" y="12" text-anchor="end">bridges →</text>'),
 ('${n.docs} peças · pontes ${((bt[n.id]||0)*1000).toFixed(1)} · influência ${((pr[n.id]||0)*1000).toFixed(1)}',
  '${n.docs} filings · bridges ${((bt[n.id]||0)*1000).toFixed(1)} · influence ${((pr[n.id]||0)*1000).toFixed(1)}'),
 ('<h3>Rankings do recorte</h3><p class="sub">Pontes e influência recalculadas só com os nós e ligações filtrados acima; mudam quando você muda o recorte.</p><div class="three"><div><h4>Pontes</h4>${li(byBt,n=>((bt[n.id]||0)*1000).toFixed(1))}</div><div><h4>Influência</h4>${li(byPr,n=>((pr[n.id]||0)*1000).toFixed(1))}</div><div><h4>Em mais processos</h4>',
  '<h3>Rankings for this view</h3><p class="sub">Bridges and influence recomputed only with the nodes and links filtered above; they change when you change the view.</p><div class="three"><div><h4>Bridges</h4>${li(byBt,n=>((bt[n.id]||0)*1000).toFixed(1))}</div><div><h4>Influence</h4>${li(byPr,n=>((pr[n.id]||0)*1000).toFixed(1))}</div><div><h4>In most proceedings</h4>'),
 ('proc. · ${n.docs} peças', 'proc. · ${n.docs} filings', "all"),
 ('<h3>Núcleos</h3><p class="sub">Comunidades (Louvain) do grafo completo, vistas pelo recorte. Nome = os dois nós mais ligados do núcleo. "Sai do núcleo" = quem tem a maior parcela de ligações para fora, isto é, a ponte típica.</p><div class="wrap"><table><tr><th>núcleo</th><th class="n">nós</th><th>composição</th><th>processos onde pesa</th><th>sai do núcleo</th><th></th></tr>',
  '<h3>Clusters</h3><p class="sub">Communities (Louvain) of the full graph, seen through this view. Name = the two most connected nodes in the cluster. "Leaves the cluster" = the node with the largest share of links pointing outward, that is, the typical bridge.</p><div class="wrap"><table><tr><th>cluster</th><th class="n">nodes</th><th>composition</th><th>proceedings where it weighs</th><th>leaves the cluster</th><th></th></tr>'),
 ('data-comm="${c}">ver no grafo</button>', 'data-comm="${c}">see in the graph</button>'),
 ('<h3>Pares fortes e específicos</h3><p class="sub">Ordenados por peças em comum × log da especificidade. Um par sobe quando divide muitas páginas <em>e</em> quando essa coincidência é rara em relação ao volume de cada um. Clique para ver as peças em que os dois aparecem.</p><div class="wrap"><table><tr><th>par</th><th class="n">peças</th><th class="n">proc.</th><th class="n" title="lift: observado / esperado">espec.</th></tr>',
  '<h3>Strong and specific pairs</h3><p class="sub">Ranked by filings in common × log of specificity. A pair rises when it shares many pages <em>and</em> when that coincidence is rare relative to each name\'s volume. Click to see the filings in which both appear.</p><div class="wrap"><table><tr><th>pair</th><th class="n">filings</th><th class="n">proc.</th><th class="n" title="lift: observed / expected">spec.</th></tr>'),
 ('<tr><td colspan=4 class=muted>nenhum par com esse filtro</td></tr>', '<tr><td colspan=4 class=muted>no pair matches this filter</td></tr>'),
 ('<h3>Quem aparece quando</h3><p class="sub">Datas citadas nas páginas em que cada nome aparece, por trimestre, desde ${RD.year}. Cada linha é normalizada pelo próprio pico: compare o formato, não a altura entre linhas. Um trimestre escuro é um período sobre o qual as peças que citam o nome falam muito, não necessariamente quando algo aconteceu.</p><div class="wrap"><table class="hm"><tr><th></th>${qs.map(k=>`<th class="rot">${k}</th>`).join("")}<th>datas</th></tr>',
  '<h3>Who appears when</h3><p class="sub">Dates cited on the pages where each name appears, by quarter, since ${RD.year}. Each row is normalised by its own peak: compare the shape, not the height across rows. A dark quarter is a period the filings citing the name talk about a lot, not necessarily when something happened.</p><div class="wrap"><table class="hm"><tr><th></th>${qs.map(k=>`<th class="rot">${k}</th>`).join("")}<th>dates</th></tr>'),
 ('${fmt(v)} datas (${tot?Math.round(v/tot*100):0}% do total do nome)', '${fmt(v)} dates (${tot?Math.round(v/tot*100):0}% of the name\'s total)'),
 ('<h3>Presença por processo</h3><p class="sub">Peças narrativas de cada processo em que o nome aparece. Linhas ordenadas por número de processos: quem atravessa o caso inteiro fica no alto; quem está num único processo costuma ser assunto de um anexo.</p>',
  '<h3>Presence by proceeding</h3><p class="sub">Narrative filings of each proceeding in which the name appears. Rows ranked by number of proceedings: whoever runs through the whole case sits at the top; whoever is in a single proceeding is usually the subject of an exhibit.</p>'),
 ('<span class=muted>${v} peças narrativas</span>', '<span class=muted>${v} narrative filings</span>'),
 ('<h3>Citados em atos judiciais</h3><p class="sub">Peças em que o nome aparece: à esquerda, decisões, despachos e petições iniciais (atos do juízo ou da acusação); à direita, as demais peças narrativas. Autoridades ficam fora, porque assinam. Ser citado numa decisão não conclui nada; diz que o juízo tratou do nome.</p>',
  '<h3>Named in judicial acts</h3><p class="sub">Filings in which the name appears: on the left, rulings, procedural orders and initial petitions (acts of the court or of the prosecution); on the right, the other narrative filings. Officials are left out, because they sign. Being named in a ruling concludes nothing; it says the court dealt with the name.</p>'),
 ('<p class="muted">Ninguém no recorte.</p></div>`', '<p class="muted">No one in this view.</p></div>`'),
 ('text-anchor="end">← em decisões e iniciais</text><text x="${cx+4}" y="12">outras peças →</text>', 'text-anchor="end">← in rulings and initial petitions</text><text x="${cx+4}" y="12">other filings →</text>'),
 ('${n.jud} em decisões/iniciais · ${n.docs-n.jud} noutras peças', '${n.jud} in rulings/initial petitions · ${n.docs-n.jud} in other filings'),
 ('<h3>Empresas recorrentes</h3><p class="sub">Empresas por número de processos em que aparecem em peças narrativas. Recorrência entre processos é sinal de fio condutor; volume dentro de um só processo costuma ser anexo.</p>',
  '<h3>Recurring companies</h3><p class="sub">Companies by the number of proceedings in which they appear in narrative filings. Recurrence across proceedings signals a thread to pull; volume within a single proceeding is usually an exhibit.</p>'),
 ('<span class=muted>${n.procs} processos · ${n.docs} peças</span>', '<span class=muted>${n.procs} proceedings · ${n.docs} filings</span>'),
 # crônicas
 ('const dateBR=d=>{ const [y,m,dd]=d.split("-"); return `${dd} de ${["janeiro","fevereiro","março","abril","maio","junho","julho","agosto","setembro","outubro","novembro","dezembro"][+m-1]} de ${y}`; };',
  'const dateBR=d=>{ const [y,m,dd]=d.split("-"); return `${+dd} ${["January","February","March","April","May","June","July","August","September","October","November","December"][+m-1]} ${y}`; };'),
 ('`<p class="muted">Carregando…</p>`', '`<p class="muted">Loading…</p>`'),
 ('md="*Não foi possível carregar o texto desta crônica.* Tente recarregar a página; se persistir, abra uma issue no repositório.";',
  'md="*The text of this chronicle could not be loaded.* Try reloading the page; if it persists, open an issue in the repository.";'),
 ('`${esc(post.serie)} · Capítulo ${post.capitulo} de ${inS.length} · ${dateBR(post.date)} · ${post.minutes} min`:`Crônica ${String(post.numero||posts.length-i).padStart(2,"0")} · ${dateBR(post.date)} · ${post.minutes} min de leitura`',
  '`${esc(post.serie)} · Chapter ${post.capitulo} of ${inS.length} · ${dateBR(post.date)} · ${post.minutes} min`:`Chronicle ${String(post.numero||posts.length-i).padStart(2,"0")} · ${dateBR(post.date)} · ${post.minutes} min read · in Portuguese`'),
 ('id="crBack">← todas as crônicas</button>', 'id="crBack">← all chronicles</button>'),
 ('<span class="muted">Opinião do autor do projeto. Números e citações apontam para os dados públicos e para o acervo do STF.</span>',
  '<span class="muted">The project author\'s opinion, translated from the Portuguese original. Numbers and citations point to the public data and to the STF archive.</span>'),
 ('<div class="cr-foot"><b>Isto é uma crônica.</b> Texto de opinião, separado da base de dados. O que é fato traz a fonte; o que é leitura é do autor. Coocorrência na mesma página não prova relação, e ninguém aqui é culpado de nada por aparecer num grafo. Erros de fato: abra uma issue no repositório. Todos os avisos: <a href="#avisos" data-nav="avisos">Avisos e direitos</a>.',
  '<div class="cr-foot"><b>This is a chronicle.</b> An opinion piece, kept separate from the database. What is fact carries its source; what is interpretation is the author\'s. Co-occurrence on the same page does not prove a relationship, and nobody here is guilty of anything for appearing in a graph. Factual errors: open an issue in the repository. All notices: <a href="#avisos" data-nav="avisos">Disclaimers and rights</a>.'),
 ('data-nav="grafo">Abrir o grafo</a><a class="btn small" href="#personagens" data-nav="personagens">Personagens</a>',
  'data-nav="grafo">Open the graph</a><a class="btn small" href="#personagens" data-nav="personagens">Profiles</a>'),
 ('<span>${inS?"capítulo anterior":"anterior"}</span>', '<span>${inS?"previous chapter":"previous"}</span>'),
 ('<span>${inS?"próximo capítulo":"próxima"}</span>', '<span>${inS?"next chapter":"next"}</span>'),
 ('document.title=`${post.title} — crônicas do autos-abertos`', 'document.title=`${post.title} — autos-abertos chronicles`'),
 ('document.title="autos-abertos — crônicas"', 'document.title="autos-abertos — chronicles"'),
 ('${x.serie?`CAPÍTULO ${x.capitulo}`:`CRÔNICA ${String(x.numero).padStart(2,"0")}`}', '${x.serie?`CHAPTER ${x.capitulo}`:`CHRONICLE ${String(x.numero).padStart(2,"0")}`}'),
 ('${xs.length} capítulos · ${xs.reduce((s,x)=>s+x.minutes,0)} min no total. Cada capítulo cobre uma parte da decisão, na ordem em que ela mesma se organiza.',
  '${xs.length} chapters · ${xs.reduce((s,x)=>s+x.minutes,0)} min in total. Each chapter covers one part of the record, in the order the record itself follows.'),
 ('<h3 class="cr-serie-t">Avulsas</h3>', '<h3 class="cr-serie-t">Standalone</h3>'),
 ('`<p class="muted">Ainda sem crônicas.</p>`', '`<p class="muted">No chronicles yet.</p>`'),
 ('/* autos-abertos — app estático. Sem backend, sem rastreamento. */', '/* autos-abertos — static app, English build. GENERATED by pipeline/build_en.py from app.js: edit app.js and pipeline/en/strings_js.py, not this file. */'),

 # títulos/subtítulos em inglês das crônicas (window.POSTS_EN, injetado por build_en.py em en.html)
 # corpo das crônicas: edição em inglês em docs/posts/en/<slug>.md, com fallback ao original em português
 ('const r=await fetch(`posts/${post.slug}.md`);', 'let r=await fetch(`posts/en/${post.slug}.md`); if(!r.ok) r=await fetch(`posts/${post.slug}.md`);'),
 ('<h1>${esc(post.title)}</h1><p class="sub">${esc(post.subtitle||"")}</p>', '<h1>${esc(EN_T(post))}</h1><p class="sub">${esc(EN_S(post))}</p>'),
 ('<h3>${esc(x.title)}</h3><p class="sub">${esc(x.subtitle||"")}</p>', '<h3>${esc(EN_T(x))}</h3><p class="sub">${esc(EN_S(x))}</p>'),
 ('`${esc(post.serie)} · Chapter', '`${esc(EN_SERIE(post.serie))} · Chapter'),
 ('<h3 class="cr-serie-t">${esc(sname)}</h3>', '<h3 class="cr-serie-t">${esc(EN_SERIE(sname))}</h3>'),
 ('<span>${inS?"previous chapter":"previous"}</span>${esc(prev.title)}', '<span>${inS?"previous chapter":"previous"}</span>${esc(EN_T(prev))}'),
 ('<span>${inS?"next chapter":"next"}</span>${esc(next.title)}', '<span>${inS?"next chapter":"next"}</span>${esc(EN_T(next))}'),
 ('document.title=`${post.title} — autos-abertos chronicles`', 'document.title=`${EN_T(post)} — autos-abertos chronicles`'),
 ('let CR=null; async function loadCR(){', 'const PEN=window.POSTS_EN||{}; const EN_T=p=>(PEN[p.slug]||{}).t||p.title, EN_S=p=>(PEN[p.slug]||{}).s||p.subtitle||"", EN_SERIE=s=>((PEN._series||{})[s])||s;\nlet CR=null; async function loadCR(){'),
]
